//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPSWebApplication.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicCatalog16_17
    {
        public string Course { get; set; }
        public string Dept { get; set; }
        public string Course_No { get; set; }
        public string Long_Title { get; set; }
        public string Credit_Hr { get; set; }
        public string SWEN { get; set; }
        public string CSCI { get; set; }
        public string SENG { get; set; }
    }
}
