//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPSWebApplication.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class capf17gswen4Entities : DbContext
    {
        public capf17gswen4Entities()
            : base("name=capf17gswen4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CPS> CPS { get; set; }
        public virtual DbSet<CPSDesignOption> CPSDesignOptions { get; set; }
        public virtual DbSet<DraftCPS> DraftCPS { get; set; }
    }
}
