//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPSWebApplication.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacultyDetail
    {
        public string FacultyId { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Departments { get; set; }
        public string AdvisorDepartment { get; set; }
        public string AdvisingStudentList { get; set; }
    }
}
